### ISSUE TITLE
Chore: Multi DB conn handling 자료 조사

### ISSUE THREAD

**Issue by TLOWAC** [kaestro/ChatApplication#19]
### 어떤 작업을 할 예정인가요?
golang chat backend 구성 과정에서 사용되는 mongoDB, postgresql, redis, kafka 등의
connection 관리 포인트에 대한 효율적인 방법이 있지 조사하고, 이를 기반으로 코드를 리팩토링 할 예정 입니다.

**Comment by TLOWAC** [comment]
## 자료 정리
### [[Blog] Organising Database Access in Go](https://www.alexedwards.net/blog/organising-database-access#closure)

설명 : 저희가 찾고 있던 대부분의 케이스 구현 예제를 확인 할 수 있던 글이었습니다.
구현 예제 : 
1. Using a global variable
2. Dependency injection
3. Wrapping the connection pool
4. Request context


### [[Github] go-zero](https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlmanager.go)

설명 : go 기반의 MSA 구현 프로젝트로 mysql, mongoDB, postgresql, redis 등 connection 에 대한 connManger 구현 예제를 확인 할 수 있었습니다.

![image](https://github.com/kaestro/ChatApplication/assets/58043975/bda267d0-7cbb-4500-817c-28a564938257)

**Comment by kaestro** [comment]
주신 자료들 잘 읽어봤습니다. 좋은 자료 찾아주셔서 감사합니다.

현재 제가 작성하고 있는 것은 첫번째 글에서 언급하는 의존성 역전을 각각의 모듈 단위로 작성하고 있었습니다. 그 부분들이 이제 LoginSessionManager 등입니다.

다만 이것이 go-zero에서 구현돼있는 것과 같은 형태로 이를 묶어서 다루는 형태로 만들 수 있으면 훨씬 효율적이고 좋을 것 같네요. 이 부분은 제가 미처 생각하지 못했는데 새로운 걸 알 수 있었습니다.

그러면 제가 이해할 때는 go-zero의 core과 같은 store를 하나 분류하고, 여기에 현재까지 작성된 모듈들을 집어넣고 관리하는 것이 좋겠냐는 제안으로 이해되는데 그게 맞으실까요?

창훈님께서는 둘을 읽고나서 어떤 식으로 설계를 구상하고 계신 것인지 궁금합니다.

**Comment by TLOWAC** [comment]
넵넵 추가해놓도록 하겠습니다!
