### ISSUE TITLE
실시간으로 작성되는 프로젝트의 구조도 update 솔루션 적용 - go diagrams

### ISSUE THREAD

**Issue by kaestro** [kaestro/ChatApplication#24]
@TLOWAC @neuma573 

**Is your feature request related to a problem? Please describe.**
diagrams와 같은 식으로 설계를 작성하는 것과 별개로, 현재 작성된 부분들의 구조에 대해서 실시간으로 트래킹되는것에 대한 솔루션이 될 수 있음.

**Describe the solution you'd like**
<https://github.com/blushft/go-diagrams?tab=readme-ov-file>
go-diagrams는 이에 대해서 적용할 경우에 실시간으로 diagram을 작성해준다고 제안함.

**Describe alternatives you've considered**
아직 생각해본 것이 없음.

**Comment by TLOWAC** [comment]
terraform 이나 pulumi 같은 Iac 인줄 알았는데 diagram 도 이런식으로 만들 수 있군요.. 신기하네요:)
